import ProjectDescription

let workspace = Workspace(
    name: "Random Pro",
    projects: ["./**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes:
                .enabled(codeCoverageMode: .all,
                         testingOptions: [
                            .parallelizable,
                            .randomExecutionOrdering])
    )
)
