disabled_rules:
- type_name
- cyclomatic_complexity
- function_body_length
- function_parameter_count
- force_unwrapping
- large_tuple
- identifier_name
- nesting
- todo
- type_body_length
- block_based_kvo
- private_over_fileprivate
- notification_center_detachment
- trailing_comma
- fatal_error_message
- unavailable_function
- nimble_operator
- implicit_getter
- valid_ibinspectable
- trailing_whitespace
- closure_parameter_position
- inclusive_language
- array_init

opt_in_rules:
#- unused_private_declaration
- array_init
- contains_over_first_not_nil
- empty_string
- empty_xctest_method
- fallthrough
- force_unwrapping
- function_default_parameter_at_end
- joined_default_parameter
- multiline_parameters
- private_outlet
- overridden_super_call
- pattern_matching_keywords
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- single_test_class
- sorted_first_last
- yoda_condition
- closure_parameter_position

file_length:
  warning: 1400
  error: 1500

line_length:
  error: 200
  warning: 190
  ignores_comments: true
  ignores_urls: true

force_cast: warning
force_try: warning

reporter: "xcode"
warning_threshold: 1000

custom_rules:
  russian_c_symbol:
    name: "No more russian C in names"
    regex: "[сС]+"
    message: "Russian С found"
    match_kinds:
      - typeidentifier
      - identifier
    severity: error
  russian_e_symbol:
    name: "No more russian E in names"
    regex: "[еЕ]+"
    message: "Russian E found"
    match_kinds:
      - typeidentifier
      - identifier
    severity: error

#  - array_init
#  - contains_over_first_not_nil
#  - empty_string
#  - empty_xctest_method
#  - fallthrough
#  - force_unwrapping
#  - function_default_parameter_at_end
#  - joined_default_parameter
#  - multiline_parameters
#  - nimble_operator
#  - private_outlet
#  - overridden_super_call
#  - pattern_matching_keywords
#  - quick_discouraged_call
#  - quick_discouraged_focused_test
#  - quick_discouraged_pending_test
#  - redundant_nil_coalescing
#  - required_enum_case
#  - single_test_class
#  - sorted_first_last
#  - unavailable_function
#  - yoda_condition
#  - unused_private_declaration
#  - cyclomatic_complexity
#  - function_body_length
#  - function_parameter_count
#  - identifier_name
#  - large_tuple
#  - line_length
#  - multiple_closures_with_trailing_closure
#  - nesting
#  - todo
#  - trailing_whitespace
#  - type_body_length
#  - block_based_kvo
#  - notification_center_detachment
#  - force_cast
#  - type_name
#  - unused_optional_binding
#  - leading_whitespace
#  - operator_whitespace
#  - shorthand_operator
#  - syntactic_sugar
#  - empty_count
#  - class_delegate_protocol
#  - closing_brace
#  - closure_parameter_position
#  - colon
#  - comma
#  - compiler_protocol_init
#  - control_statement
#  - custom_rules
#  - discarded_notification_center_observer
#  - discouraged_direct_init
#  - dynamic_inline
#  - empty_enum_arguments
#  - empty_parameters
#  - empty_parentheses_with_trailing_closure
#  - file_length
#  - for_where
#  - force_try
#  - generic_type_name
#  - implicit_getter
#  - is_disjoint
#  - legacy_cggeometry_functions
#  - legacy_constant
#  - legacy_constructor
#  - legacy_nsgeometry_functions
#  - mark
#  - no_fallthrough_only
#  - notification_center_detachment
#  - opening_brace
#  - private_over_fileprivate
#  - private_unit_test
#  - protocol_property_accessors_order
#  - redundant_discardable_let
#  - redundant_optional_initialization
#  - redundant_set_access_control
#  - redundant_string_enum_value
#  - redundant_void_return
#  - return_arrow_whitespace
#  - statement_position
#  - superfluous_disable_command
#  - switch_case_alignment
#  - trailing_comma
#  - trailing_newline
#  - trailing_semicolon
#  - type_body_length
#  - unneeded_break_in_switch
#  - unused_closure_parameter
#  - unused_enumerated
#  - valid_ibinspectable
#  - vertical_parameter_alignment
#  - vertical_whitespace
#  - void_return
#  - weak_delegate
#  - xctfail_message
#  - let_var_whitespace
#  - attributes
#  - closure_end_indentation
#  - closure_spacing
#  - conditional_returns_on_newline
#  - convenience_type
#  - discouraged_object_literal
#  - discouraged_optional_boolean
#  - discouraged_optional_collection
#  - explicit_acl
#  - explicit_enum_raw_value
#  - explicit_init
#  - explicit_top_level_acl
#  - explicit_type_interface
#  - extension_access_modifier
#  - fatal_error_message
#  - file_header
#  - file_name
#  - first_where
#  - implicit_return
#  - implicitly_unwrapped_optional
#  - literal_expression_end_indentation
#  - lower_acl_than_parent
#  - modifier_order
#  - multiline_arguments
#  - multiline_function_chains
#  - no_extension_access_modifier
#  - no_grouping_extension
#  - number_separator
#  - object_literal
#  - operator_usage_whitespace
#  - override_in_extension
#  - prefixed_toplevel_constant
#  - private_action
#  - prohibited_super_call
#  - sorted_imports
#  - strict_fileprivate
#  - switch_case_on_newline
#  - trailing_closure
#  - unneeded_parentheses_in_closure_argument
#  - untyped_error_in_catch
#  - vertical_parameter_alignment_on_call
