default_platform(:ios)

platform :ios do

  desc "Build the app"
  lane :build do
    build_ios_app(
      workspace: "Random.xcworkspace",
      scheme: "Random",
      export_method: "app-store", # или "ad-hoc", в зависимости от типа распространения
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE_UUID"]
        },
        signingStyle: "manual",
        signingCertificate: ENV["SIGNING_CERTIFICATE"]
      }
    )
  end

  desc "Upload IPA to App Store Connect"
  lane :upload_app_to_app_store do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"],
      in_house: false,
      is_key_content_base64: true
    )

    pilot(
      api_key: api_key,
      ipa: "Random.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
