name: Build and sign iOS app

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set up Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Send Telegram notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python send_telegram.py "🚀 New pull request created! 🚀
        Author: ${{ github.actor }}
        Branch: ${{ github.head_ref }}
        Pull Request URL: ${{ github.event.pull_request.html_url }}"

    - name: Import certificate and provisioning profile
      env:
        IOS_CERTIFICATE: ${{ secrets.IOS_CERTIFICATE }}
        IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        echo "$IOS_CERTIFICATE" | base64 --decode > /tmp/Certificate.p12
        echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > /tmp/Profile.mobileprovision
        security create-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain
        security set-keychain-settings -lut 3600 ~/Library/Keychains/build.keychain
        security import /tmp/Certificate.p12 -k ~/Library/Keychains/build.keychain -P "" -T /usr/bin/codesign -A
        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp /tmp/Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        PROVISIONING_PROFILE_UUID=$(grep -a -A 1 "UUID" /tmp/Profile.mobileprovision | tail -1 | awk -F '<string>' '{print $2}' | awk -F '</string>' '{print $1}')
        echo "PROVISIONING_PROFILE_UUID=$PROVISIONING_PROFILE_UUID" >> $GITHUB_ENV

    - name: Set up Tuist
      run: |
        curl -Ls https://install.tuist.io | bash

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Set up fastlane
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: bundle exec danger

    - name: Tuist fetch
      run: |
        tuist fetch

    - name: Tuist generate
      run: |
        tuist generate

    - name: Build and sign the app
      env:
        DEVELOPMENT_TEAM: "34VDSPZYU9"
      run: |
        xcodebuild -workspace Random.xcworkspace \
                   -scheme Random \
                   -sdk iphoneos \
                   -configuration Release \
                   -derivedDataPath derived_data \
                   build \
                   CODE_SIGN_STYLE=Manual \
                   DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                   PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_UUID \
                   CODE_SIGN_IDENTITY="Apple Distribution: Vitalii Sosin (34VDSPZYU9)" \
                   CODE_SIGNING_ALLOWED=YES
